# fly.toml app configuration file generated for falling-brook-544 on 2023-07-26T13:50:11-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "falling-brook-544"
primary_region = "gru"

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
