# fly.toml app configuration file generated for ermailer2 on 2023-07-26T23:42:43-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ermailer2"
primary_region = "gru"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
